[build]
command = "next build" 	
commandOrigin = "config"
environment = - NEXT_PRIVATE_TARGET
publish = "/opt/build/repo/.next"	
publishOrigin =  "config"

[[plugins]]
package = "@netlify/plugin-nextjs"